package com.jotta.jogodavelha;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JButton;

/**
 *
 * @author Jorge Paulo Santos
 */
public class JogoDaVelha extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JogoDaVelha.class.getName());
    private final Intermediario inter;
    private final Random gerador;
    private String letra, simboloAtivaRobo;
    private final boolean[] arrayAtiva;
    private final JButton[] arrayBotoes;
    /**
     * Creates new form Main
     */
    public JogoDaVelha() {
        initComponents();
        this.inter = new Intermediario();
        this.gerador = new Random();
        this.simboloAtivaRobo = "X";
        arrayAtiva = new boolean[]{
        true, true, true, true,
        true, true, true, true, true};
        arrayBotoes = new JButton[] { 
        btn1, btn2, btn3, 
        btn4, btn5, btn6, 
        btn7, btn8, btn9 
        };
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnReset = new javax.swing.JToggleButton();
        btnSair = new javax.swing.JButton();
        lblSaida = new javax.swing.JLabel();
        boxOponente = new javax.swing.JComboBox<>();
        lblOponente = new javax.swing.JLabel();
        btnIniciarRobo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnReset.setText("Reiniciar");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblSaida.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblSaida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        boxOponente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maquina", "Outro Jogador" }));

        lblOponente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOponente.setText("Oponente");

        btnIniciarRobo.setText("Iniciar com a Maquina");
        btnIniciarRobo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarRoboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(btnReset)
                            .addGap(254, 254, 254)
                            .addComponent(btnSair))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btnIniciarRobo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblOponente, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3)
                            .addComponent(boxOponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                        .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxOponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOponente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciarRobo))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnReset))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if(arrayAtiva[0]){
            String simbolo = inter.obterProximoSímbolo();
            arrayBotoes[0].setForeground(
                "X".equals(simbolo) ? Color.RED : Color.BLUE
            );
            arrayBotoes[0].setText(simbolo);
            inter.registrarJogada(0, 0, simbolo);
            verificaFimJogo();
            arrayAtiva[0] = false;
            verificarVezJogar();
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if(arrayAtiva[1]){
            String simbolo = inter.obterProximoSímbolo();
            arrayBotoes[1].setForeground(
                "X".equals(simbolo) ? Color.RED : Color.BLUE
            );
            arrayBotoes[1].setText(simbolo);
            inter.registrarJogada(0, 1, simbolo);
            verificaFimJogo();
            arrayAtiva[1] = false;
            verificarVezJogar();
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if(arrayAtiva[2]){
            String simbolo = inter.obterProximoSímbolo();
            arrayBotoes[2].setForeground(
                "X".equals(simbolo) ? Color.RED : Color.BLUE
            );
            arrayBotoes[2].setText(simbolo);
            inter.registrarJogada(0, 2, simbolo);
            verificaFimJogo();
            arrayAtiva[2] = false;
            verificarVezJogar();
        }   
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if(arrayAtiva[3]){
            String simbolo = inter.obterProximoSímbolo();
            arrayBotoes[3].setForeground(
                "X".equals(simbolo) ? Color.RED : Color.BLUE
            );
            arrayBotoes[3].setText(simbolo);
            inter.registrarJogada(1, 0, simbolo);
            verificaFimJogo();
            arrayAtiva[3] = false;
            verificarVezJogar();
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        if(arrayAtiva[4]){
            String simbolo = inter.obterProximoSímbolo();
            arrayBotoes[4].setForeground(
                "X".equals(simbolo) ? Color.RED : Color.BLUE
            );
            arrayBotoes[4].setText(simbolo);
            inter.registrarJogada(1, 1, simbolo);
            verificaFimJogo();
            arrayAtiva[4] = false;
            verificarVezJogar();
        }   
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        if(arrayAtiva[5]){
            String simbolo = inter.obterProximoSímbolo();
            arrayBotoes[5].setForeground(
                "X".equals(simbolo) ? Color.RED : Color.BLUE
            );
            arrayBotoes[5].setText(simbolo);
            inter.registrarJogada(1, 2, simbolo);
            verificaFimJogo();
            arrayAtiva[5] = false;
            verificarVezJogar();
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        if(arrayAtiva[6]){
            String simbolo = inter.obterProximoSímbolo();
            arrayBotoes[6].setForeground(
                "X".equals(simbolo) ? Color.RED : Color.BLUE
            );
            arrayBotoes[6].setText(simbolo);
            inter.registrarJogada(2, 0, simbolo);
            verificaFimJogo();
            arrayAtiva[6] = false;
            verificarVezJogar();
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        if(arrayAtiva[7]){
            String simbolo = inter.obterProximoSímbolo();
            arrayBotoes[7].setForeground(
                "X".equals(simbolo) ? Color.RED : Color.BLUE
            );
            arrayBotoes[7].setText(simbolo);
            inter.registrarJogada(2, 1, simbolo);
            verificaFimJogo();
            arrayAtiva[7] = false;
            verificarVezJogar();
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        if(arrayAtiva[8]){
            String simbolo = inter.obterProximoSímbolo();
            arrayBotoes[8].setForeground(
                "X".equals(simbolo) ? Color.RED : Color.BLUE
            );
            arrayBotoes[8].setText(simbolo);
            inter.registrarJogada(2, 2, simbolo);
            verificaFimJogo();
            arrayAtiva[8] = false;
            verificarVezJogar();
        }
    }//GEN-LAST:event_btn9ActionPerformed
    
    private void verificaFimJogo(){
        String vencedor = inter.getVencedor();
        if(inter.getFimJogo()){
            if("e".equals(vencedor)){
                lblSaida.setForeground(Color.MAGENTA);
                lblSaida.setText("Empate!!!!");
            }else{
                lblSaida.setForeground(
                    "X".equals(vencedor)               
                      ? Color.RED                  
                      : Color.BLUE                 
                    );
                lblSaida.setText("O Jogador "+vencedor+" é o vencedor!");
            }
            
        }
    }
    
    private void robo() {
        // Cria uma lista de índices disponíveis
        List<Integer> indicesDisponiveis = new ArrayList<>();
        for (int i = 0; i < arrayAtiva.length; i++) {
            if (arrayAtiva[i]) {
                indicesDisponiveis.add(i);
            }
        }

        // Se houver índices disponíveis, escolhe um aleatoriamente e clica
        if (!indicesDisponiveis.isEmpty()) {
            int indiceAleatorio = indicesDisponiveis.get(gerador.nextInt(indicesDisponiveis.size()));
            arrayBotoes[indiceAleatorio].doClick();
        }
    }
    
    
    
    private void verificarVezJogar(){
        String simbolo = inter.getSimboloAtual();
        visualizarComponentes(false);
        if(boxOponente.getSelectedIndex()==0){
            if(simbolo.equals(simboloAtivaRobo) && !inter.getFimJogo()){
                robo();
            }
        }
    }
    
    private void visualizarComponentes(boolean visivel){
        boxOponente.setVisible(visivel);
        lblOponente.setVisible(visivel);
        btnIniciarRobo.setVisible(visivel);
    }
    
    private void limparBtn(){
        for (JButton botao : arrayBotoes) {
        botao.setText("");
        }
    }
    private void liberaBtn(){
        for(int i=0; i<9; i++){
            arrayAtiva[i]=true;
        }
    }

    
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        inter.resetar();
        limparBtn();
        liberaBtn();
        lblSaida.setText("");
        this.simboloAtivaRobo="X";
        visualizarComponentes(true);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnIniciarRoboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarRoboActionPerformed
        // TODO add your handling code here:
        this.simboloAtivaRobo="O";
        visualizarComponentes(false);
        robo();
    }//GEN-LAST:event_btnIniciarRoboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JogoDaVelha().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxOponente;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnIniciarRobo;
    private javax.swing.JToggleButton btnReset;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel lblOponente;
    private javax.swing.JLabel lblSaida;
    // End of variables declaration//GEN-END:variables
}
